jobs:
- job:
  displayName: vs2017-win2016
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python36:
        python.version: '3.6'

  steps:
  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH


  - script: python -m pip install --upgrade pip setuptools wheel
    displayName: 'Install tools'

  - script: |
      conda create --yes --quiet --name env-from-yaml
      call activate env-from-yaml
      conda env create -f environment.yml
    displayName: Install Anaconda packages
