jobs:
- job:
  displayName: vs2017-win2016
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python36:
        python.version: '3.6'

  steps:
  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH

  - script: conda create --yes --quiet --name myEnvironment
    displayName: Create Anaconda environment

  - script: |
      call activate myEnvironment
      conda install --yes --quiet --name myEnvironment python=%PYTHON_VERSION% spacy
    displayName: Install Anaconda packages
